export interface Fair {
  id: string;
  name: string;
  postcode: string;
  nextDate: string;
  entryFee: string;
  stallFee: string;
  openingTime: string;
  closingTime: string;
  website?: string;
  email: string;
  displayEmailPublicly?: boolean;
  categories: string[];
phone?: string;
  address: string;
  lat: number;
  lng: number;
  hours: string;
  frequency: string;
  images: string[];
  featured: boolean;
  busyScore: number;
  description: string;
  verified: boolean;
  lastUpdated: string;
  social: Record<string, string>;
  parking: boolean;
  toilets: boolean;
  foodStalls: boolean;
  dogFriendly: boolean;
  wheelchairAccessible: boolean;
  indoor: boolean;
  weatherSafe: boolean;
  estimatedStalls: number;
  estimatedVisitors: number;
  acceptsCard: boolean;
  acceptsCash: boolean;
}
export const fairs: Fair[] = [];
