# ============================
# FLIPPILOT TRIM SCRIPT (SAFE)
# ============================

# --- Dealer AI Brain Screens ---
Remove-Item "src/features/dealer-ai/screens/BuyerBehaviourBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/CrossCountryStockStrategyScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerCultureBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerEconomicsBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerForecastBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerLoyaltyBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerMultiverseBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerNetworkBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerProfitabilityBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerPsychologyBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerRiskBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerStrategyBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerStressBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/DealerWorkforceBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/EconomicsBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/FlipProfitBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/GlobalGovernanceBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/GlobalIntelligenceScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/GlobalMarketStressScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/LeadIntelligenceBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/MarketplaceRankingBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/OEMIntelligenceBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/PredictiveDemandBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/PricingBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/SupplyChainStressScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehicleConditionBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehicleForecastBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehicleHistoryBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehicleIntelligenceBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehicleInvestmentBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehicleLifecycleBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehiclePortfolioBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehicleReliabilityBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehicleRiskBrainScreen.tsx"
Remove-Item "src/features/dealer-ai/screens/VehicleSentimentBrainScreen.tsx"

# --- Dealer Intelligence Hubs ---
Remove-Item "src/dealer/intelligence/DealerCultureHub.tsx"
Remove-Item "src/dealer/intelligence/DealerDiagnosticsHub.tsx"
Remove-Item "src/dealer/intelligence/DealerEconomicsHub.tsx"
Remove-Item "src/dealer/intelligence/DealerFinanceHub.tsx"
Remove-Item "src/dealer/intelligence/DealerLoyaltyHub.tsx"
Remove-Item "src/dealer/intelligence/DealerMarketingHub.tsx"
Remove-Item "src/dealer/intelligence/DealerMultiverseHub.tsx"
Remove-Item "src/dealer/intelligence/DealerPredictiveEngine.tsx"
Remove-Item "src/dealer/intelligence/DealerPsychologyHub.tsx"
Remove-Item "src/dealer/intelligence/DealerSalesHub.tsx"
Remove-Item "src/dealer/intelligence/DealerStockHub.tsx"
Remove-Item "src/dealer/intelligence/DealerStrategyHub.tsx"
Remove-Item "src/dealer/intelligence/DealerUniverseHub.tsx"
Remove-Item "src/dealer/intelligence/DealerWorkforceHub.tsx"
Remove-Item "src/dealer/intelligence/GlobalIntelligenceHub.tsx"

# --- MOT AI Widgets ---
Remove-Item "src/vehicle-ai/MotAiChainReaction.tsx"
Remove-Item "src/vehicle-ai/MotAiCostEstimator.tsx"
Remove-Item "src/vehicle-ai/MotAiFailureBreakdown.tsx"
Remove-Item "src/vehicle-ai/MotAiFutureTimeline.tsx"
Remove-Item "src/vehicle-ai/MotAiHealthGauge.tsx"
Remove-Item "src/vehicle-ai/MotAiMileageProjection.tsx"
Remove-Item "src/vehicle-ai/MotAiNeuralRiskMap.tsx"
Remove-Item "src/vehicle-ai/MotAiOutcomeSimulator.tsx"
Remove-Item "src/vehicle-ai/MotAiRadarChart.tsx"
Remove-Item "src/vehicle-ai/MotAiRecommendations.tsx"

# --- Marketplace AI Widgets ---
Remove-Item "src/components/marketplace/PriceDropPredictor.tsx"
Remove-Item "src/components/marketplace/SponsoredCard.tsx"
Remove-Item "src/components/marketplace/ListingQualityScore.tsx"

# --- Dealer UI Clutter ---
Remove-Item "src/components/dealer/MatchResultCard.tsx"
Remove-Item "src/components/dealer/MotRiskScanner.tsx"
Remove-Item "src/components/dealer/RiskScoreCard.tsx"
Remove-Item "src/components/dealer/SupernovaCard.tsx"
Remove-Item "src/components/dealer/SupernovaSectionHeader.tsx"
