export type EmploymentType = "full_time" | "part_time";
export type WeekDay = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

export const WEEK_DAYS: WeekDay[] = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"];
export const WEEK_DAY_LABELS: Record<WeekDay, string> = {
  mon: "Mon",
  tue: "Tue",
  wed: "Wed",
  thu: "Thu",
  fri: "Fri",
  sat: "Sat",
  sun: "Sun",
};

export interface WorkPattern {
  userId: string;
  userName: string;
  employmentType: EmploymentType;
  targetWeeklyHours: number;
  availableDays: WeekDay[];
  // Days per year, set per person since this genuinely varies firm to
  // firm (and sometimes person to person) — not derived from
  // employmentType, always an explicit manager-set number.
  holidayEntitlementDays: number;
}

export type LeaveType = "holiday" | "sick" | "other";
export type LeaveStatus = "pending" | "approved" | "declined";

export interface LeaveRequest {
  id: string;
  userId: string;
  userName: string;
  type: LeaveType;
  startDate: string;
  endDate: string;
  status: LeaveStatus;
  notes?: string;
  requestedAt: string;
  decidedAt: string | null;
  decidedByName: string | null;
}

export interface Shift {
  id: string;
  userId: string;
  userName: string;
  date: string;
  start: string;
  end: string;
  notes?: string;
  autoGenerated: boolean;
  createdAt: string;
}

export interface RotaSettings {
  openDays: WeekDay[];
  openTime: string;
  closeTime: string;
}
