import { useState } from "react";
import { usePlanner } from "@/context/PlannerContext";
import { useAuth } from "@/context/AuthContext";
import { sendNotification } from "@/notifications/notificationStorage.web";
import type { Shift } from "@/planner/plannerTypes";

interface ShiftEditModalProps {
  userId: string;
  userName: string;
  date: string;
  existing?: Shift;
  onClose: () => void;
}

export default function ShiftEditModal({ userId, userName, date, existing, onClose }: ShiftEditModalProps) {
  const { saveShift, removeShift } = usePlanner();
  const { user } = useAuth();
  const [start, setStart] = useState(existing?.start ?? "09:00");
  const [end, setEnd] = useState(existing?.end ?? "17:00");
  const [notes, setNotes] = useState(existing?.notes ?? "");
  const [saving, setSaving] = useState(false);

  // Every manual add/edit/remove here notifies the affected staff
  // member directly — this is exactly the "mid-week update for
  // sickness cover" case: a manager reshuffles the rota and the
  // person whose shift changed finds out without having to check the
  // grid themselves. Skipped when editing your own shift to avoid
  // self-notifying.
  function notifyIfNotSelf(title: string, message: string, type: "info" | "warning") {
    if (userId === user?.id) return;
    sendNotification({ userId, title, message, type }).catch(() => {});
  }

  async function handleSave() {
    if (end <= start) return;
    setSaving(true);
    const shift: Shift = {
      id: existing?.id ?? crypto.randomUUID(),
      userId,
      userName,
      date,
      start,
      end,
      ...(notes.trim() ? { notes: notes.trim() } : {}),
      autoGenerated: existing?.autoGenerated ?? false,
      createdAt: existing?.createdAt ?? new Date().toISOString(),
    };
    await saveShift(shift);
    notifyIfNotSelf(
      existing ? "Your shift was updated" : "New shift added",
      `${date}: ${start}–${end}${notes.trim() ? ` (${notes.trim()})` : ""}`,
      "info"
    );
    setSaving(false);
    onClose();
  }

  async function handleDelete() {
    if (!existing) return;
    setSaving(true);
    await removeShift(existing.id);
    notifyIfNotSelf("Shift removed", `Your shift on ${date} (${existing.start}–${existing.end}) has been removed.`, "warning");
    setSaving(false);
    onClose();
  }

  return (
    <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4">
      <div className="bg-black/80 border border-white/10 p-6 rounded-xl w-full max-w-sm">
        <h2 className="text-white/80 text-xl font-semibold mb-1">{userName}</h2>
        <p className="text-white/50 text-sm mb-4">{date}</p>

        <label className="text-white/60 text-sm">Start</label>
        <input
          type="time"
          value={start}
          onChange={e => setStart(e.target.value)}
          className="w-full p-2 rounded bg-black/40 border border-white/10 text-white/80 mb-4"
        />

        <label className="text-white/60 text-sm">End</label>
        <input
          type="time"
          value={end}
          onChange={e => setEnd(e.target.value)}
          className="w-full p-2 rounded bg-black/40 border border-white/10 text-white/80 mb-4"
        />
        {end <= start && <p className="text-red-400 text-xs mb-4">End time must be after start time.</p>}

        <label className="text-white/60 text-sm">Notes (optional)</label>
        <input
          type="text"
          value={notes}
          onChange={e => setNotes(e.target.value)}
          className="w-full p-2 rounded bg-black/40 border border-white/10 text-white/80 mb-4"
        />

        <div className="flex justify-between items-center gap-3">
          {existing ? (
            <button
              onClick={handleDelete}
              disabled={saving}
              className="px-4 py-2 rounded bg-red-600/20 text-red-300 border border-red-500/40 hover:bg-red-600/30"
            >
              Remove Shift
            </button>
          ) : (
            <span />
          )}
          <div className="flex gap-3">
            <button onClick={onClose} className="px-4 py-2 rounded bg-white/10 text-white/70 hover:bg-white/20">
              Cancel
            </button>
            <button
              onClick={handleSave}
              disabled={saving || end <= start}
              className="px-4 py-2 rounded font-semibold bg-yellow-500 text-black hover:bg-yellow-400 disabled:bg-gray-600 disabled:text-gray-300"
            >
              Save
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
