import { randomUUID } from "crypto";
import { Express, Request } from "express";
import {
  readTenantCollection,
  writeTenantCollection,
  readTenantDoc,
  writeTenantDoc,
} from "../db";
import { requireStaffRole, type AuthUser } from "../auth";
import { itemsFromBody } from "../wholeListGuard";

export type EmploymentType = "full_time" | "part_time";
export type WeekDay = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

// One per real staff account — their contracted weekly hours and which
// days they're normally available. This is the input the auto-rota
// generator below uses to build a starting-point schedule around
// actual full-time vs part-time staff rather than guessing.
export interface WorkPattern {
  userId: string;
  userName: string;
  employmentType: EmploymentType;
  targetWeeklyHours: number;
  availableDays: WeekDay[];
  holidayEntitlementDays: number;
}

export type LeaveType = "holiday" | "sick" | "other";
export type LeaveStatus = "pending" | "approved" | "declined";

export interface LeaveRequest {
  id: string;
  userId: string;
  userName: string;
  type: LeaveType;
  startDate: string;
  endDate: string;
  status: LeaveStatus;
  notes?: string;
  requestedAt: string;
  decidedAt: string | null;
  decidedByName: string | null;
}

export interface Shift {
  id: string;
  userId: string;
  userName: string;
  date: string;
  start: string;
  end: string;
  notes?: string;
  autoGenerated: boolean;
  createdAt: string;
}

export interface RotaSettings {
  openDays: WeekDay[];
  openTime: string;
  closeTime: string;
}

export const DEFAULT_ROTA_SETTINGS: RotaSettings = {
  openDays: ["mon", "tue", "wed", "thu", "fri", "sat"],
  openTime: "09:00",
  closeTime: "18:00",
};

const WEEK_DAYS: WeekDay[] = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"];

function authedUser(req: Request): AuthUser {
  return (req as Request & { user: AuthUser }).user;
}

function isManagerOrOwner(user: AuthUser): boolean {
  return user.role === "owner" || user.staffRole === "manager";
}

function toMinutes(hhmm: string): number {
  const [h, m] = hhmm.split(":").map(Number);
  return (h ?? 0) * 60 + (m ?? 0);
}

function toHHMM(mins: number): string {
  const h = Math.floor(mins / 60).toString().padStart(2, "0");
  const m = Math.round(mins % 60).toString().padStart(2, "0");
  return `${h}:${m}`;
}

export function toDateKeyLocal(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

// The 7 dates of the week starting at `weekStart` (expected to already
// be a Monday, yyyy-mm-dd) — walks forward day by day rather than
// trusting Date's own week arithmetic across a DST boundary, and
// formats each result from the Date's LOCAL fields rather than
// toISOString() (which is UTC and silently rolls back to the previous
// day whenever the server's timezone is ahead of UTC — this exact bug
// put real generated shifts on the wrong days entirely).
function datesForWeek(weekStart: string): { date: string; day: WeekDay }[] {
  const start = new Date(`${weekStart}T00:00:00`);
  return WEEK_DAYS.map((day, i) => {
    const d = new Date(start);
    d.setDate(start.getDate() + i);
    return { date: toDateKeyLocal(d), day };
  });
}

function isOnApprovedLeave(date: string, leave: LeaveRequest[], userId: string): boolean {
  return leave.some(
    l => l.userId === userId && l.status === "approved" && l.startDate <= date && date <= l.endDate
  );
}

export default function registerPlannerRoutes(app: Express) {
  // WORK PATTERNS
  app.get("/work-patterns", (req, res) => {
    const user = authedUser(req);
    res.json({ ok: true, items: readTenantCollection<WorkPattern>(user.dealershipId, "workPatterns") });
  });

  // Setting contracted hours/availability is manager territory, same
  // tier as managing the staff roster itself.
  app.put("/work-patterns", requireStaffRole("manager"), (req, res) => {
    const user = authedUser(req);
    const items = itemsFromBody(req, res);
    if (!items) return;
    writeTenantCollection(user.dealershipId, "workPatterns", items);
    res.json({ ok: true, items });
  });

  // LEAVE — holiday needs manager sign-off before it blocks the rota;
  // sick is a record of something that's already happening, not a
  // request, so it's approved immediately.
  app.get("/leave", (req, res) => {
    const user = authedUser(req);
    res.json({ ok: true, items: readTenantCollection<LeaveRequest>(user.dealershipId, "leave") });
  });

  app.post("/leave", (req, res) => {
    const user = authedUser(req);
    const { type, startDate, endDate, notes } = req.body ?? {};

    if (
      !["holiday", "sick", "other"].includes(type) ||
      typeof startDate !== "string" ||
      typeof endDate !== "string"
    ) {
      return res.status(400).json({ ok: false, error: "type, startDate and endDate are required" });
    }
    if (endDate < startDate) {
      return res.status(400).json({ ok: false, error: "endDate cannot be before startDate" });
    }

    const items = readTenantCollection<LeaveRequest>(user.dealershipId, "leave");
    const autoApprove = type === "sick";
    const entry: LeaveRequest = {
      id: randomUUID(),
      userId: user.id,
      userName: user.name,
      type,
      startDate,
      endDate,
      status: autoApprove ? "approved" : "pending",
      ...(typeof notes === "string" && notes.trim() ? { notes: notes.trim() } : {}),
      requestedAt: new Date().toISOString(),
      decidedAt: autoApprove ? new Date().toISOString() : null,
      decidedByName: autoApprove ? user.name : null,
    };
    const updated = [...items, entry];
    writeTenantCollection(user.dealershipId, "leave", updated);
    res.json({ ok: true, entry, items: updated });
  });

  // Approve/decline — manager territory, same tier as correcting a
  // time clock entry.
  app.put("/leave/:id", requireStaffRole("manager"), (req, res) => {
    const user = authedUser(req);
    const { status } = req.body ?? {};
    if (status !== "approved" && status !== "declined") {
      return res.status(400).json({ ok: false, error: "status must be approved or declined" });
    }

    const items = readTenantCollection<LeaveRequest>(user.dealershipId, "leave");
    if (!items.some(l => l.id === req.params.id)) {
      return res.status(404).json({ ok: false, error: "Leave request not found" });
    }

    const updated = items.map(l =>
      l.id === req.params.id
        ? { ...l, status: status as LeaveStatus, decidedAt: new Date().toISOString(), decidedByName: user.name }
        : l
    );
    writeTenantCollection(user.dealershipId, "leave", updated);
    res.json({ ok: true, items: updated });
  });

  // A staff member can withdraw their own still-pending request; a
  // manager/owner can remove any leave record.
  app.delete("/leave/:id", (req, res) => {
    const user = authedUser(req);
    const items = readTenantCollection<LeaveRequest>(user.dealershipId, "leave");
    const target = items.find(l => l.id === req.params.id);
    if (!target) {
      return res.status(404).json({ ok: false, error: "Leave request not found" });
    }

    const isOwnPending = target.userId === user.id && target.status === "pending";
    if (!isManagerOrOwner(user) && !isOwnPending) {
      return res.status(403).json({ ok: false, error: "You can only withdraw your own pending requests" });
    }

    const updated = items.filter(l => l.id !== req.params.id);
    writeTenantCollection(user.dealershipId, "leave", updated);
    res.json({ ok: true, items: updated });
  });

  // ROTA SETTINGS — which days the business is open and its opening
  // hours, the window the auto-generator schedules shifts inside.
  app.get("/rota-settings", (req, res) => {
    const user = authedUser(req);
    res.json({
      ok: true,
      settings: readTenantDoc<RotaSettings>(user.dealershipId, "rotaSettings", DEFAULT_ROTA_SETTINGS),
    });
  });

  app.put("/rota-settings", requireStaffRole("manager"), (req, res) => {
    const user = authedUser(req);
    const { openDays, openTime, closeTime } = req.body ?? {};
    if (!Array.isArray(openDays) || typeof openTime !== "string" || typeof closeTime !== "string") {
      return res.status(400).json({ ok: false, error: "openDays, openTime and closeTime are required" });
    }
    const settings: RotaSettings = { openDays, openTime, closeTime };
    writeTenantDoc(user.dealershipId, "rotaSettings", settings);
    res.json({ ok: true, settings });
  });

  // SHIFTS — the actual rota. Manual edits go through the same
  // full-array PUT pattern as jobs/staff; /shifts/generate below is a
  // separate, additive suggestion engine, not the only way to write
  // this collection.
  app.get("/shifts", (req, res) => {
    const user = authedUser(req);
    res.json({ ok: true, items: readTenantCollection<Shift>(user.dealershipId, "shifts") });
  });

  app.put("/shifts", requireStaffRole("manager"), (req, res) => {
    const user = authedUser(req);
    const items = itemsFromBody(req, res);
    if (!items) return;
    writeTenantCollection(user.dealershipId, "shifts", items);
    res.json({ ok: true, items });
  });

  // Auto-generates a starting-point rota for one week. Deliberately a
  // simple, explainable heuristic rather than a full constraint
  // solver: for each staff member with a work pattern, spread their
  // contracted weekly hours evenly across their available days that
  // week, skipping any day covered by approved leave and any day that
  // already has a manually-set shift for them — so re-running it, or
  // running it after manual tweaks, only fills the gaps rather than
  // clobbering existing work. A manager reviews/edits the result
  // afterwards; this is a first draft, not a final answer.
  app.post("/shifts/generate", requireStaffRole("manager"), (req, res) => {
    const user = authedUser(req);
    const { weekStart } = req.body ?? {};
    if (typeof weekStart !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(weekStart)) {
      return res.status(400).json({ ok: false, error: "weekStart (yyyy-mm-dd, a Monday) is required" });
    }

    const patterns = readTenantCollection<WorkPattern>(user.dealershipId, "workPatterns");
    const leave = readTenantCollection<LeaveRequest>(user.dealershipId, "leave");
    const existingShifts = readTenantCollection<Shift>(user.dealershipId, "shifts");
    const settings = readTenantDoc<RotaSettings>(user.dealershipId, "rotaSettings", DEFAULT_ROTA_SETTINGS);

    const week = datesForWeek(weekStart);
    const openWindowMinutes = toMinutes(settings.closeTime) - toMinutes(settings.openTime);

    const generated: Shift[] = [];

    for (const pattern of patterns) {
      const availableOpenDays = week.filter(
        w => settings.openDays.includes(w.day) && pattern.availableDays.includes(w.day)
      );
      if (availableOpenDays.length === 0) continue;

      const targetMinutes = pattern.targetWeeklyHours * 60;
      const perDayMinutes = Math.min(openWindowMinutes, Math.round(targetMinutes / availableOpenDays.length));
      if (perDayMinutes <= 0) continue;

      for (const { date } of availableOpenDays) {
        const alreadyHasShift = existingShifts.some(s => s.userId === pattern.userId && s.date === date);
        if (alreadyHasShift || isOnApprovedLeave(date, leave, pattern.userId)) continue;

        generated.push({
          id: randomUUID(),
          userId: pattern.userId,
          userName: pattern.userName,
          date,
          start: settings.openTime,
          end: toHHMM(toMinutes(settings.openTime) + perDayMinutes),
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        });
      }
    }

    const updated = [...existingShifts, ...generated];
    writeTenantCollection(user.dealershipId, "shifts", updated);
    res.json({ ok: true, generated, items: updated });
  });
}
